export const homeObjOne = {
	id: "about",
	lightBg: true,
	lightText: true,
	lightTextDesc: true,
	topLine: "About Me",
	headline: "some text about me......",
	description: "some text about desc....",
	buttonLabel: "Go Home",
	imgStart: false,
	img: require("../../images/cool-coder.svg").default,
	alt: "Man coding",
	dark: true,
	primary: true,
	darkText: false,
};
